name: My workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send dispatch
        run: |
         curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/actions-producer-consumer/consumer/dispatches --data '{"event_type": "build_application"}'
