name: My workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send dispatch
        run: |
         curl --fail -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -X POST https://api.github.com/repos/actions-producer-consumer/consumer/dispatches -H 'Accept: application/vnd.github.everest-preview+json' --data "{\"event_type\": \"consume\"}"
